[build]
  command = "bun install "npm install --legacy-peer-deps && bun run generate""npm install --legacy-peer-deps && bun run generate" bun run generate"
  publish = ".output/public"

[build.environment]
  BUN_VERSION = "latest"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "unsafe-none"
