[build]
  command = "bun install && bun run generate"
  publish = ".output/public"

[build.environment]
  BUN_VERSION = "latest"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "unsafe-none"
